# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1.xci
# IP: The module: 'PS_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1.xci
# IP: The module: 'PS_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/snn_1206/snn_1206.srcs/sources_1/bd/PS/ip/PS_clk_wiz_0_1/PS_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
