// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fc_snn_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.534500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=1488,HLS_SYN_LUT=3626,HLS_VERSION=2019_2}" *)

module fc_snn_top (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

reg in_stream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] n_steps;
wire    clear_state;
reg   [31:0] v_mem_V_0;
reg   [31:0] v_mem_V_1;
reg   [31:0] v_mem_V_2;
reg   [31:0] v_mem_V_3;
reg   [31:0] v_mem_V_4;
reg   [31:0] v_mem_V_5;
reg   [31:0] v_mem_V_6;
reg   [31:0] v_mem_V_7;
reg   [31:0] v_mem_V_8;
reg   [31:0] v_mem_V_9;
wire   [11:0] W_FC_V_0_address0;
reg    W_FC_V_0_ce0;
wire   [5:0] W_FC_V_0_q0;
wire   [11:0] W_FC_V_1_address0;
reg    W_FC_V_1_ce0;
wire   [5:0] W_FC_V_1_q0;
wire   [11:0] W_FC_V_2_address0;
reg    W_FC_V_2_ce0;
wire   [5:0] W_FC_V_2_q0;
wire   [11:0] W_FC_V_3_address0;
reg    W_FC_V_3_ce0;
wire   [5:0] W_FC_V_3_q0;
wire   [11:0] W_FC_V_4_address0;
reg    W_FC_V_4_ce0;
wire   [5:0] W_FC_V_4_q0;
wire   [11:0] W_FC_V_5_address0;
reg    W_FC_V_5_ce0;
wire   [5:0] W_FC_V_5_q0;
wire   [11:0] W_FC_V_6_address0;
reg    W_FC_V_6_ce0;
wire   [5:0] W_FC_V_6_q0;
wire   [11:0] W_FC_V_7_address0;
reg    W_FC_V_7_ce0;
wire   [6:0] W_FC_V_7_q0;
wire   [11:0] W_FC_V_8_address0;
reg    W_FC_V_8_ce0;
wire   [6:0] W_FC_V_8_q0;
wire   [11:0] W_FC_V_9_address0;
reg    W_FC_V_9_ce0;
wire   [5:0] W_FC_V_9_q0;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln43_fu_562_p2;
wire   [0:0] icmp_ln64_fu_620_p2;
reg    out_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] icmp_ln60_1_reg_1675;
reg   [0:0] icmp_ln60_1_reg_1675_pp0_iter2_reg;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] icmp_ln60_1_reg_1675_pp0_iter3_reg;
reg   [43:0] indvar_flatten_reg_330;
reg   [30:0] t_0_reg_341;
reg   [31:0] acc_V_9_0_reg_352;
reg   [31:0] acc_V_8_0_reg_364;
reg   [31:0] acc_V_7_0_reg_376;
reg   [31:0] acc_V_6_0_reg_388;
reg   [31:0] acc_V_5_0_reg_400;
reg   [31:0] acc_V_4_0_reg_412;
reg   [31:0] acc_V_3_0_reg_424;
reg   [31:0] acc_V_2_0_reg_436;
reg   [31:0] acc_V_1_0_reg_448;
reg   [31:0] acc_V_0_0_reg_460;
reg   [12:0] i_0_reg_472;
wire   [31:0] add_ln96_fu_543_p2;
reg   [31:0] add_ln96_reg_1574;
wire   [43:0] tmp_fu_549_p3;
reg   [43:0] tmp_reg_1579;
reg   [0:0] icmp_ln43_reg_1584;
reg    ap_predicate_op71_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_state5_io;
wire    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln43_reg_1584_pp0_iter1_reg;
wire   [43:0] add_ln43_fu_567_p2;
wire   [0:0] icmp_ln60_fu_576_p2;
reg   [0:0] icmp_ln60_reg_1593;
wire   [30:0] select_ln43_12_fu_604_p3;
reg   [30:0] select_ln43_12_reg_1607;
wire   [4:0] bvh_d_index_fu_616_p1;
reg   [4:0] bvh_d_index_reg_1612;
wire   [12:0] i_fu_654_p2;
reg   [12:0] i_reg_1670;
wire   [0:0] icmp_ln60_1_fu_660_p2;
reg   [0:0] icmp_ln60_1_reg_1675_pp0_iter1_reg;
wire   [0:0] y_last_V_fu_666_p2;
reg   [0:0] y_last_V_reg_1679;
reg   [0:0] y_last_V_reg_1679_pp0_iter1_reg;
reg   [0:0] y_last_V_reg_1679_pp0_iter2_reg;
wire   [31:0] acc_9_V_1_fu_865_p3;
reg   [31:0] acc_9_V_1_reg_1684;
reg    ap_enable_reg_pp0_iter1;
wire   [31:0] acc_8_V_1_fu_873_p3;
reg   [31:0] acc_8_V_1_reg_1690;
wire   [31:0] acc_7_V_1_fu_881_p3;
reg   [31:0] acc_7_V_1_reg_1696;
wire   [31:0] acc_6_V_1_fu_889_p3;
reg   [31:0] acc_6_V_1_reg_1702;
wire   [31:0] acc_5_V_1_fu_897_p3;
reg   [31:0] acc_5_V_1_reg_1708;
wire   [31:0] acc_4_V_1_fu_905_p3;
reg   [31:0] acc_4_V_1_reg_1714;
wire   [31:0] acc_3_V_1_fu_913_p3;
reg   [31:0] acc_3_V_1_reg_1720;
wire   [31:0] acc_2_V_1_fu_921_p3;
reg   [31:0] acc_2_V_1_reg_1726;
wire   [31:0] acc_1_V_1_fu_929_p3;
reg   [31:0] acc_1_V_1_reg_1732;
wire   [31:0] acc_0_V_1_fu_937_p3;
reg   [31:0] acc_0_V_1_reg_1738;
wire   [0:0] icmp_ln891_fu_964_p2;
reg   [0:0] icmp_ln891_reg_1744;
wire   [0:0] icmp_ln891_1_fu_1009_p2;
reg   [0:0] icmp_ln891_1_reg_1749;
wire   [0:0] icmp_ln891_2_fu_1054_p2;
reg   [0:0] icmp_ln891_2_reg_1754;
wire   [0:0] icmp_ln891_3_fu_1099_p2;
reg   [0:0] icmp_ln891_3_reg_1759;
wire   [0:0] icmp_ln891_4_fu_1144_p2;
reg   [0:0] icmp_ln891_4_reg_1764;
wire   [0:0] icmp_ln891_5_fu_1189_p2;
reg   [0:0] icmp_ln891_5_reg_1769;
wire   [0:0] icmp_ln891_6_fu_1234_p2;
reg   [0:0] icmp_ln891_6_reg_1774;
wire   [0:0] icmp_ln891_7_fu_1279_p2;
reg   [0:0] icmp_ln891_7_reg_1779;
wire   [0:0] icmp_ln891_8_fu_1324_p2;
reg   [0:0] icmp_ln891_8_reg_1784;
wire   [0:0] icmp_ln891_9_fu_1369_p2;
reg   [0:0] icmp_ln891_9_reg_1789;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg   [30:0] ap_phi_mux_t_0_phi_fu_345_p4;
reg   [31:0] ap_phi_mux_acc_V_9_0_phi_fu_356_p4;
reg   [31:0] ap_phi_mux_acc_V_8_0_phi_fu_368_p4;
reg   [31:0] ap_phi_mux_acc_V_7_0_phi_fu_380_p4;
reg   [31:0] ap_phi_mux_acc_V_6_0_phi_fu_392_p4;
reg   [31:0] ap_phi_mux_acc_V_5_0_phi_fu_404_p4;
reg   [31:0] ap_phi_mux_acc_V_4_0_phi_fu_416_p4;
reg   [31:0] ap_phi_mux_acc_V_3_0_phi_fu_428_p4;
reg   [31:0] ap_phi_mux_acc_V_2_0_phi_fu_440_p4;
reg   [31:0] ap_phi_mux_acc_V_1_0_phi_fu_452_p4;
reg   [31:0] ap_phi_mux_acc_V_0_0_phi_fu_464_p4;
reg   [12:0] ap_phi_mux_i_0_phi_fu_476_p4;
wire   [63:0] zext_ln73_fu_640_p1;
wire   [0:0] clear_state_read_read_fu_158_p2;
wire   [31:0] select_ln85_fu_976_p3;
wire   [31:0] select_ln891_fu_1021_p3;
wire   [31:0] select_ln891_2_fu_1066_p3;
wire   [31:0] select_ln891_4_fu_1111_p3;
wire   [31:0] select_ln891_6_fu_1156_p3;
wire   [31:0] select_ln891_8_fu_1201_p3;
wire   [31:0] select_ln891_10_fu_1246_p3;
wire   [31:0] select_ln891_12_fu_1291_p3;
wire   [31:0] select_ln891_14_fu_1336_p3;
wire   [31:0] select_ln891_16_fu_1381_p3;
reg   [31:0] p_Val2_s_fu_154;
wire   [31:0] select_ln43_10_fu_582_p3;
reg    ap_block_pp0_stage0_01001;
wire   [30:0] add_ln43_1_fu_598_p2;
wire   [12:0] select_ln43_11_fu_590_p3;
wire   [31:0] zext_ln43_fu_612_p1;
wire   [31:0] zext_ln64_fu_741_p1;
wire   [31:0] shl_ln791_fu_747_p2;
wire   [31:0] and_ln791_fu_753_p2;
wire   [31:0] select_ln43_9_fu_734_p3;
wire  signed [31:0] sext_ln68_fu_765_p1;
wire   [31:0] select_ln43_8_fu_727_p3;
wire  signed [31:0] sext_ln68_1_fu_775_p1;
wire   [31:0] select_ln43_7_fu_720_p3;
wire  signed [31:0] sext_ln68_2_fu_785_p1;
wire   [31:0] select_ln43_6_fu_713_p3;
wire  signed [31:0] sext_ln68_3_fu_795_p1;
wire   [31:0] select_ln43_5_fu_706_p3;
wire  signed [31:0] sext_ln68_4_fu_805_p1;
wire   [31:0] select_ln43_4_fu_699_p3;
wire  signed [31:0] sext_ln68_5_fu_815_p1;
wire   [31:0] select_ln43_3_fu_692_p3;
wire  signed [31:0] sext_ln68_6_fu_825_p1;
wire   [31:0] select_ln43_2_fu_685_p3;
wire  signed [31:0] sext_ln68_7_fu_835_p1;
wire   [31:0] select_ln43_1_fu_678_p3;
wire  signed [31:0] sext_ln68_8_fu_845_p1;
wire   [31:0] select_ln43_fu_671_p3;
wire  signed [31:0] sext_ln68_9_fu_855_p1;
wire   [0:0] p_Result_s_fu_759_p2;
wire   [31:0] acc_9_V_fu_859_p2;
wire   [31:0] acc_8_V_fu_849_p2;
wire   [31:0] acc_7_V_fu_839_p2;
wire   [31:0] acc_6_V_fu_829_p2;
wire   [31:0] acc_5_V_fu_819_p2;
wire   [31:0] acc_4_V_fu_809_p2;
wire   [31:0] acc_3_V_fu_799_p2;
wire   [31:0] acc_2_V_fu_789_p2;
wire   [31:0] acc_1_V_fu_779_p2;
wire   [31:0] acc_0_V_fu_769_p2;
wire   [31:0] add_ln700_fu_949_p2;
wire   [23:0] tmp_3_fu_954_p4;
wire   [31:0] add_ln701_fu_970_p2;
wire   [31:0] add_ln700_1_fu_994_p2;
wire   [23:0] tmp_4_fu_999_p4;
wire   [31:0] add_ln701_1_fu_1015_p2;
wire   [31:0] add_ln700_2_fu_1039_p2;
wire   [23:0] tmp_5_fu_1044_p4;
wire   [31:0] add_ln701_2_fu_1060_p2;
wire   [31:0] add_ln700_3_fu_1084_p2;
wire   [23:0] tmp_7_fu_1089_p4;
wire   [31:0] add_ln701_3_fu_1105_p2;
wire   [31:0] add_ln700_4_fu_1129_p2;
wire   [23:0] tmp_9_fu_1134_p4;
wire   [31:0] add_ln701_4_fu_1150_p2;
wire   [31:0] add_ln700_5_fu_1174_p2;
wire   [23:0] tmp_11_fu_1179_p4;
wire   [31:0] add_ln701_5_fu_1195_p2;
wire   [31:0] add_ln700_6_fu_1219_p2;
wire   [23:0] tmp_13_fu_1224_p4;
wire   [31:0] add_ln701_6_fu_1240_p2;
wire   [31:0] add_ln700_7_fu_1264_p2;
wire   [23:0] tmp_15_fu_1269_p4;
wire   [31:0] add_ln701_7_fu_1285_p2;
wire   [31:0] add_ln700_8_fu_1309_p2;
wire   [23:0] tmp_17_fu_1314_p4;
wire   [31:0] add_ln701_8_fu_1330_p2;
wire   [31:0] add_ln700_9_fu_1354_p2;
wire   [23:0] tmp_19_fu_1359_p4;
wire   [31:0] add_ln701_9_fu_1375_p2;
wire   [0:0] xor_ln85_fu_1395_p2;
wire   [1:0] zext_ln700_fu_1400_p1;
wire   [1:0] tmp_2_fu_1404_p3;
wire   [1:0] select_ln891_1_fu_1412_p3;
wire   [2:0] tmp_6_fu_1423_p3;
wire   [31:0] zext_ln891_fu_1419_p1;
wire   [31:0] zext_ln816_fu_1431_p1;
wire   [31:0] select_ln891_3_fu_1435_p3;
reg   [31:0] tmp_8_fu_1442_p4;
wire   [31:0] select_ln891_5_fu_1452_p3;
reg   [31:0] tmp_10_fu_1459_p4;
wire   [31:0] select_ln891_7_fu_1469_p3;
reg   [31:0] tmp_12_fu_1476_p4;
wire   [31:0] select_ln891_9_fu_1486_p3;
reg   [31:0] tmp_14_fu_1493_p4;
wire   [31:0] select_ln891_11_fu_1503_p3;
reg   [31:0] tmp_16_fu_1510_p4;
wire   [31:0] select_ln891_13_fu_1520_p3;
reg   [31:0] tmp_18_fu_1527_p4;
wire   [31:0] select_ln891_15_fu_1537_p3;
reg   [31:0] tmp_20_fu_1544_p4;
wire    ap_CS_fsm_state7;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int;
wire    in_stream_TVALID_int;
reg    in_stream_TREADY_int;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int;
reg    out_stream_TVALID_int;
wire    out_stream_TREADY_int;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 v_mem_V_0 = 32'd0;
#0 v_mem_V_1 = 32'd0;
#0 v_mem_V_2 = 32'd0;
#0 v_mem_V_3 = 32'd0;
#0 v_mem_V_4 = 32'd0;
#0 v_mem_V_5 = 32'd0;
#0 v_mem_V_6 = 32'd0;
#0 v_mem_V_7 = 32'd0;
#0 v_mem_V_8 = 32'd0;
#0 v_mem_V_9 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

fc_snn_top_W_FC_V_0 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_0_address0),
    .ce0(W_FC_V_0_ce0),
    .q0(W_FC_V_0_q0)
);

fc_snn_top_W_FC_V_1 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_1_address0),
    .ce0(W_FC_V_1_ce0),
    .q0(W_FC_V_1_q0)
);

fc_snn_top_W_FC_V_2 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_2_address0),
    .ce0(W_FC_V_2_ce0),
    .q0(W_FC_V_2_q0)
);

fc_snn_top_W_FC_V_3 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_3_address0),
    .ce0(W_FC_V_3_ce0),
    .q0(W_FC_V_3_q0)
);

fc_snn_top_W_FC_V_4 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_4_address0),
    .ce0(W_FC_V_4_ce0),
    .q0(W_FC_V_4_q0)
);

fc_snn_top_W_FC_V_5 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_5_address0),
    .ce0(W_FC_V_5_ce0),
    .q0(W_FC_V_5_q0)
);

fc_snn_top_W_FC_V_6 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_6_address0),
    .ce0(W_FC_V_6_ce0),
    .q0(W_FC_V_6_q0)
);

fc_snn_top_W_FC_V_7 #(
    .DataWidth( 7 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_7_address0),
    .ce0(W_FC_V_7_ce0),
    .q0(W_FC_V_7_q0)
);

fc_snn_top_W_FC_V_8 #(
    .DataWidth( 7 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_8_address0),
    .ce0(W_FC_V_8_ce0),
    .q0(W_FC_V_8_q0)
);

fc_snn_top_W_FC_V_9 #(
    .DataWidth( 6 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
W_FC_V_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(W_FC_V_9_address0),
    .ce0(W_FC_V_9_ce0),
    .q0(W_FC_V_9_q0)
);

fc_snn_top_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
fc_snn_top_CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .n_steps(n_steps),
    .clear_state(clear_state)
);

regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int),
    .vld_out(in_stream_TVALID_int),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int),
    .vld_in(out_stream_TVALID_int),
    .ack_in(out_stream_TREADY_int),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(y_last_V_reg_1679_pp0_iter2_reg),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_0_0_reg_460 <= acc_0_V_1_reg_1738;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_0_0_reg_460 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_1_0_reg_448 <= acc_1_V_1_reg_1732;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_1_0_reg_448 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_2_0_reg_436 <= acc_2_V_1_reg_1726;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_2_0_reg_436 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_3_0_reg_424 <= acc_3_V_1_reg_1720;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_3_0_reg_424 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_4_0_reg_412 <= acc_4_V_1_reg_1714;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_4_0_reg_412 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_5_0_reg_400 <= acc_5_V_1_reg_1708;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_5_0_reg_400 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_6_0_reg_388 <= acc_6_V_1_reg_1702;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_6_0_reg_388 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_7_0_reg_376 <= acc_7_V_1_reg_1696;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_7_0_reg_376 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_8_0_reg_364 <= acc_8_V_1_reg_1690;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_8_0_reg_364 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0))) begin
        acc_V_9_0_reg_352 <= acc_9_V_1_reg_1684;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        acc_V_9_0_reg_352 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_1584 == 1'd0))) begin
        i_0_reg_472 <= i_reg_1670;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_472 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_fu_562_p2 == 1'd0))) begin
        indvar_flatten_reg_330 <= add_ln43_fu_567_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_330 <= 44'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln64_fu_620_p2 == 1'd1) & (icmp_ln43_fu_562_p2 == 1'd0))) begin
        p_Val2_s_fu_154 <= in_stream_TDATA_int;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln64_fu_620_p2 == 1'd0) & (icmp_ln43_fu_562_p2 == 1'd0))) begin
        p_Val2_s_fu_154 <= select_ln43_10_fu_582_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_Val2_s_fu_154 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_1584 == 1'd0))) begin
        t_0_reg_341 <= select_ln43_12_reg_1607;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t_0_reg_341 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_0 <= select_ln85_fu_976_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_0 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_1 <= select_ln891_fu_1021_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_1 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_2 <= select_ln891_2_fu_1066_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_2 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_3 <= select_ln891_4_fu_1111_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_3 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_4 <= select_ln891_6_fu_1156_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_4 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_5 <= select_ln891_8_fu_1201_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_5 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_6 <= select_ln891_10_fu_1246_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_6 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_7 <= select_ln891_12_fu_1291_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_7 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_8 <= select_ln891_14_fu_1336_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_8 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        v_mem_V_9 <= select_ln891_16_fu_1381_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (clear_state_read_read_fu_158_p2 == 1'd1) & (ap_start == 1'b1))) begin
        v_mem_V_9 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_1584 == 1'd0))) begin
        acc_0_V_1_reg_1738 <= acc_0_V_1_fu_937_p3;
        acc_1_V_1_reg_1732 <= acc_1_V_1_fu_929_p3;
        acc_2_V_1_reg_1726 <= acc_2_V_1_fu_921_p3;
        acc_3_V_1_reg_1720 <= acc_3_V_1_fu_913_p3;
        acc_4_V_1_reg_1714 <= acc_4_V_1_fu_905_p3;
        acc_5_V_1_reg_1708 <= acc_5_V_1_fu_897_p3;
        acc_6_V_1_reg_1702 <= acc_6_V_1_fu_889_p3;
        acc_7_V_1_reg_1696 <= acc_7_V_1_fu_881_p3;
        acc_8_V_1_reg_1690 <= acc_8_V_1_fu_873_p3;
        acc_9_V_1_reg_1684 <= acc_9_V_1_fu_865_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        add_ln96_reg_1574 <= add_ln96_fu_543_p2;
        tmp_reg_1579[43 : 12] <= tmp_fu_549_p3[43 : 12];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_fu_562_p2 == 1'd0))) begin
        bvh_d_index_reg_1612 <= bvh_d_index_fu_616_p1;
        icmp_ln60_1_reg_1675 <= icmp_ln60_1_fu_660_p2;
        icmp_ln60_reg_1593 <= icmp_ln60_fu_576_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_fu_562_p2 == 1'd0))) begin
        i_reg_1670 <= i_fu_654_p2;
        select_ln43_12_reg_1607 <= select_ln43_12_fu_604_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln43_reg_1584 <= icmp_ln43_fu_562_p2;
        icmp_ln43_reg_1584_pp0_iter1_reg <= icmp_ln43_reg_1584;
        icmp_ln60_1_reg_1675_pp0_iter1_reg <= icmp_ln60_1_reg_1675;
        y_last_V_reg_1679_pp0_iter1_reg <= y_last_V_reg_1679;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln60_1_reg_1675_pp0_iter2_reg <= icmp_ln60_1_reg_1675_pp0_iter1_reg;
        icmp_ln60_1_reg_1675_pp0_iter3_reg <= icmp_ln60_1_reg_1675_pp0_iter2_reg;
        y_last_V_reg_1679_pp0_iter2_reg <= y_last_V_reg_1679_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_1_reg_1675_pp0_iter1_reg == 1'd1))) begin
        icmp_ln891_1_reg_1749 <= icmp_ln891_1_fu_1009_p2;
        icmp_ln891_2_reg_1754 <= icmp_ln891_2_fu_1054_p2;
        icmp_ln891_3_reg_1759 <= icmp_ln891_3_fu_1099_p2;
        icmp_ln891_4_reg_1764 <= icmp_ln891_4_fu_1144_p2;
        icmp_ln891_5_reg_1769 <= icmp_ln891_5_fu_1189_p2;
        icmp_ln891_6_reg_1774 <= icmp_ln891_6_fu_1234_p2;
        icmp_ln891_7_reg_1779 <= icmp_ln891_7_fu_1279_p2;
        icmp_ln891_8_reg_1784 <= icmp_ln891_8_fu_1324_p2;
        icmp_ln891_9_reg_1789 <= icmp_ln891_9_fu_1369_p2;
        icmp_ln891_reg_1744 <= icmp_ln891_fu_964_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_1_fu_660_p2 == 1'd1) & (icmp_ln43_fu_562_p2 == 1'd0))) begin
        y_last_V_reg_1679 <= y_last_V_fu_666_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_0_ce0 = 1'b1;
    end else begin
        W_FC_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_1_ce0 = 1'b1;
    end else begin
        W_FC_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_2_ce0 = 1'b1;
    end else begin
        W_FC_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_3_ce0 = 1'b1;
    end else begin
        W_FC_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_4_ce0 = 1'b1;
    end else begin
        W_FC_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_5_ce0 = 1'b1;
    end else begin
        W_FC_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_6_ce0 = 1'b1;
    end else begin
        W_FC_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_7_ce0 = 1'b1;
    end else begin
        W_FC_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_8_ce0 = 1'b1;
    end else begin
        W_FC_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_FC_V_9_ce0 = 1'b1;
    end else begin
        W_FC_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln43_fu_562_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_0_0_phi_fu_464_p4 = acc_0_V_1_reg_1738;
    end else begin
        ap_phi_mux_acc_V_0_0_phi_fu_464_p4 = acc_V_0_0_reg_460;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_1_0_phi_fu_452_p4 = acc_1_V_1_reg_1732;
    end else begin
        ap_phi_mux_acc_V_1_0_phi_fu_452_p4 = acc_V_1_0_reg_448;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_2_0_phi_fu_440_p4 = acc_2_V_1_reg_1726;
    end else begin
        ap_phi_mux_acc_V_2_0_phi_fu_440_p4 = acc_V_2_0_reg_436;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_3_0_phi_fu_428_p4 = acc_3_V_1_reg_1720;
    end else begin
        ap_phi_mux_acc_V_3_0_phi_fu_428_p4 = acc_V_3_0_reg_424;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_4_0_phi_fu_416_p4 = acc_4_V_1_reg_1714;
    end else begin
        ap_phi_mux_acc_V_4_0_phi_fu_416_p4 = acc_V_4_0_reg_412;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_5_0_phi_fu_404_p4 = acc_5_V_1_reg_1708;
    end else begin
        ap_phi_mux_acc_V_5_0_phi_fu_404_p4 = acc_V_5_0_reg_400;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_6_0_phi_fu_392_p4 = acc_6_V_1_reg_1702;
    end else begin
        ap_phi_mux_acc_V_6_0_phi_fu_392_p4 = acc_V_6_0_reg_388;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_7_0_phi_fu_380_p4 = acc_7_V_1_reg_1696;
    end else begin
        ap_phi_mux_acc_V_7_0_phi_fu_380_p4 = acc_V_7_0_reg_376;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_8_0_phi_fu_368_p4 = acc_8_V_1_reg_1690;
    end else begin
        ap_phi_mux_acc_V_8_0_phi_fu_368_p4 = acc_V_8_0_reg_364;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln43_reg_1584_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_acc_V_9_0_phi_fu_356_p4 = acc_9_V_1_reg_1684;
    end else begin
        ap_phi_mux_acc_V_9_0_phi_fu_356_p4 = acc_V_9_0_reg_352;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_1584 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_i_0_phi_fu_476_p4 = i_reg_1670;
    end else begin
        ap_phi_mux_i_0_phi_fu_476_p4 = i_0_reg_472;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln43_reg_1584 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_t_0_phi_fu_345_p4 = select_ln43_12_reg_1607;
    end else begin
        ap_phi_mux_t_0_phi_fu_345_p4 = t_0_reg_341;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln64_fu_620_p2 == 1'd1) & (icmp_ln43_fu_562_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (regslice_both_in_stream_V_data_V_U_ack_in == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op71_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY_int = 1'b1;
    end else begin
        in_stream_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln60_1_reg_1675_pp0_iter2_reg == 1'd1))) begin
        out_stream_TVALID_int = 1'b1;
    end else begin
        out_stream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln43_fu_562_p2 == 1'd1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln43_fu_562_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W_FC_V_0_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_1_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_2_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_3_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_4_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_5_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_6_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_7_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_8_address0 = zext_ln73_fu_640_p1;

assign W_FC_V_9_address0 = zext_ln73_fu_640_p1;

assign acc_0_V_1_fu_937_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_9_fu_734_p3 : acc_0_V_fu_769_p2);

assign acc_0_V_fu_769_p2 = ($signed(select_ln43_9_fu_734_p3) + $signed(sext_ln68_fu_765_p1));

assign acc_1_V_1_fu_929_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_8_fu_727_p3 : acc_1_V_fu_779_p2);

assign acc_1_V_fu_779_p2 = ($signed(select_ln43_8_fu_727_p3) + $signed(sext_ln68_1_fu_775_p1));

assign acc_2_V_1_fu_921_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_7_fu_720_p3 : acc_2_V_fu_789_p2);

assign acc_2_V_fu_789_p2 = ($signed(select_ln43_7_fu_720_p3) + $signed(sext_ln68_2_fu_785_p1));

assign acc_3_V_1_fu_913_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_6_fu_713_p3 : acc_3_V_fu_799_p2);

assign acc_3_V_fu_799_p2 = ($signed(select_ln43_6_fu_713_p3) + $signed(sext_ln68_3_fu_795_p1));

assign acc_4_V_1_fu_905_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_5_fu_706_p3 : acc_4_V_fu_809_p2);

assign acc_4_V_fu_809_p2 = ($signed(select_ln43_5_fu_706_p3) + $signed(sext_ln68_4_fu_805_p1));

assign acc_5_V_1_fu_897_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_4_fu_699_p3 : acc_5_V_fu_819_p2);

assign acc_5_V_fu_819_p2 = ($signed(select_ln43_4_fu_699_p3) + $signed(sext_ln68_5_fu_815_p1));

assign acc_6_V_1_fu_889_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_3_fu_692_p3 : acc_6_V_fu_829_p2);

assign acc_6_V_fu_829_p2 = ($signed(select_ln43_3_fu_692_p3) + $signed(sext_ln68_6_fu_825_p1));

assign acc_7_V_1_fu_881_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_2_fu_685_p3 : acc_7_V_fu_839_p2);

assign acc_7_V_fu_839_p2 = ($signed(select_ln43_2_fu_685_p3) + $signed(sext_ln68_7_fu_835_p1));

assign acc_8_V_1_fu_873_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_1_fu_678_p3 : acc_8_V_fu_849_p2);

assign acc_8_V_fu_849_p2 = ($signed(select_ln43_1_fu_678_p3) + $signed(sext_ln68_8_fu_845_p1));

assign acc_9_V_1_fu_865_p3 = ((p_Result_s_fu_759_p2[0:0] === 1'b1) ? select_ln43_fu_671_p3 : acc_9_V_fu_859_p2);

assign acc_9_V_fu_859_p2 = ($signed(select_ln43_fu_671_p3) + $signed(sext_ln68_9_fu_855_p1));

assign add_ln43_1_fu_598_p2 = (31'd1 + ap_phi_mux_t_0_phi_fu_345_p4);

assign add_ln43_fu_567_p2 = (indvar_flatten_reg_330 + 44'd1);

assign add_ln700_1_fu_994_p2 = (v_mem_V_1 + acc_1_V_1_reg_1732);

assign add_ln700_2_fu_1039_p2 = (v_mem_V_2 + acc_2_V_1_reg_1726);

assign add_ln700_3_fu_1084_p2 = (v_mem_V_3 + acc_3_V_1_reg_1720);

assign add_ln700_4_fu_1129_p2 = (v_mem_V_4 + acc_4_V_1_reg_1714);

assign add_ln700_5_fu_1174_p2 = (v_mem_V_5 + acc_5_V_1_reg_1708);

assign add_ln700_6_fu_1219_p2 = (v_mem_V_6 + acc_6_V_1_reg_1702);

assign add_ln700_7_fu_1264_p2 = (v_mem_V_7 + acc_7_V_1_reg_1696);

assign add_ln700_8_fu_1309_p2 = (v_mem_V_8 + acc_8_V_1_reg_1690);

assign add_ln700_9_fu_1354_p2 = (v_mem_V_9 + acc_9_V_1_reg_1684);

assign add_ln700_fu_949_p2 = (v_mem_V_0 + acc_0_V_1_reg_1738);

assign add_ln701_1_fu_1015_p2 = ($signed(add_ln700_1_fu_994_p2) + $signed(32'd4294967040));

assign add_ln701_2_fu_1060_p2 = ($signed(add_ln700_2_fu_1039_p2) + $signed(32'd4294967040));

assign add_ln701_3_fu_1105_p2 = ($signed(add_ln700_3_fu_1084_p2) + $signed(32'd4294967040));

assign add_ln701_4_fu_1150_p2 = ($signed(add_ln700_4_fu_1129_p2) + $signed(32'd4294967040));

assign add_ln701_5_fu_1195_p2 = ($signed(add_ln700_5_fu_1174_p2) + $signed(32'd4294967040));

assign add_ln701_6_fu_1240_p2 = ($signed(add_ln700_6_fu_1219_p2) + $signed(32'd4294967040));

assign add_ln701_7_fu_1285_p2 = ($signed(add_ln700_7_fu_1264_p2) + $signed(32'd4294967040));

assign add_ln701_8_fu_1330_p2 = ($signed(add_ln700_8_fu_1309_p2) + $signed(32'd4294967040));

assign add_ln701_9_fu_1375_p2 = ($signed(add_ln700_9_fu_1354_p2) + $signed(32'd4294967040));

assign add_ln701_fu_970_p2 = ($signed(add_ln700_fu_949_p2) + $signed(32'd4294967040));

assign add_ln96_fu_543_p2 = ($signed(n_steps) + $signed(32'd4294967295));

assign and_ln791_fu_753_p2 = (shl_ln791_fu_747_p2 & p_Val2_s_fu_154);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((in_stream_TVALID_int == 1'b0) & (ap_predicate_op71_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((in_stream_TVALID_int == 1'b0) & (ap_predicate_op71_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((in_stream_TVALID_int == 1'b0) & (ap_predicate_op71_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((in_stream_TVALID_int == 1'b0) & (ap_predicate_op71_read_state2 == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((out_stream_TREADY_int == 1'b0) & (icmp_ln60_1_reg_1675_pp0_iter2_reg == 1'd1));
end

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((out_stream_TREADY_int == 1'b0) & (icmp_ln60_1_reg_1675_pp0_iter3_reg == 1'd1));
end

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op71_read_state2 = ((icmp_ln64_fu_620_p2 == 1'd1) & (icmp_ln43_fu_562_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bvh_d_index_fu_616_p1 = select_ln43_11_fu_590_p3[4:0];

assign clear_state_read_read_fu_158_p2 = clear_state;

assign i_fu_654_p2 = (select_ln43_11_fu_590_p3 + 13'd1);

assign icmp_ln43_fu_562_p2 = ((indvar_flatten_reg_330 == tmp_reg_1579) ? 1'b1 : 1'b0);

assign icmp_ln60_1_fu_660_p2 = ((i_fu_654_p2 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_576_p2 = ((ap_phi_mux_i_0_phi_fu_476_p4 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_620_p2 = ((bvh_d_index_fu_616_p1 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln891_1_fu_1009_p2 = (($signed(tmp_4_fu_999_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_2_fu_1054_p2 = (($signed(tmp_5_fu_1044_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_3_fu_1099_p2 = (($signed(tmp_7_fu_1089_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_4_fu_1144_p2 = (($signed(tmp_9_fu_1134_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_5_fu_1189_p2 = (($signed(tmp_11_fu_1179_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_6_fu_1234_p2 = (($signed(tmp_13_fu_1224_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_7_fu_1279_p2 = (($signed(tmp_15_fu_1269_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_8_fu_1324_p2 = (($signed(tmp_17_fu_1314_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_9_fu_1369_p2 = (($signed(tmp_19_fu_1359_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_964_p2 = (($signed(tmp_3_fu_954_p4) < $signed(24'd1)) ? 1'b1 : 1'b0);

assign out_stream_TDATA_int = ((icmp_ln891_9_reg_1789[0:0] === 1'b1) ? select_ln891_15_fu_1537_p3 : tmp_20_fu_1544_p4);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign p_Result_s_fu_759_p2 = ((and_ln791_fu_753_p2 == 32'd0) ? 1'b1 : 1'b0);

assign select_ln43_10_fu_582_p3 = ((icmp_ln60_fu_576_p2[0:0] === 1'b1) ? 32'd0 : p_Val2_s_fu_154);

assign select_ln43_11_fu_590_p3 = ((icmp_ln60_fu_576_p2[0:0] === 1'b1) ? 13'd0 : ap_phi_mux_i_0_phi_fu_476_p4);

assign select_ln43_12_fu_604_p3 = ((icmp_ln60_fu_576_p2[0:0] === 1'b1) ? add_ln43_1_fu_598_p2 : ap_phi_mux_t_0_phi_fu_345_p4);

assign select_ln43_1_fu_678_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_8_0_phi_fu_368_p4);

assign select_ln43_2_fu_685_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_7_0_phi_fu_380_p4);

assign select_ln43_3_fu_692_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_6_0_phi_fu_392_p4);

assign select_ln43_4_fu_699_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_5_0_phi_fu_404_p4);

assign select_ln43_5_fu_706_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_4_0_phi_fu_416_p4);

assign select_ln43_6_fu_713_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_3_0_phi_fu_428_p4);

assign select_ln43_7_fu_720_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_2_0_phi_fu_440_p4);

assign select_ln43_8_fu_727_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_1_0_phi_fu_452_p4);

assign select_ln43_9_fu_734_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_0_0_phi_fu_464_p4);

assign select_ln43_fu_671_p3 = ((icmp_ln60_reg_1593[0:0] === 1'b1) ? 32'd0 : ap_phi_mux_acc_V_9_0_phi_fu_356_p4);

assign select_ln85_fu_976_p3 = ((icmp_ln891_fu_964_p2[0:0] === 1'b1) ? add_ln700_fu_949_p2 : add_ln701_fu_970_p2);

assign select_ln891_10_fu_1246_p3 = ((icmp_ln891_6_fu_1234_p2[0:0] === 1'b1) ? add_ln700_6_fu_1219_p2 : add_ln701_6_fu_1240_p2);

assign select_ln891_11_fu_1503_p3 = ((icmp_ln891_6_reg_1774[0:0] === 1'b1) ? select_ln891_9_fu_1486_p3 : tmp_14_fu_1493_p4);

assign select_ln891_12_fu_1291_p3 = ((icmp_ln891_7_fu_1279_p2[0:0] === 1'b1) ? add_ln700_7_fu_1264_p2 : add_ln701_7_fu_1285_p2);

assign select_ln891_13_fu_1520_p3 = ((icmp_ln891_7_reg_1779[0:0] === 1'b1) ? select_ln891_11_fu_1503_p3 : tmp_16_fu_1510_p4);

assign select_ln891_14_fu_1336_p3 = ((icmp_ln891_8_fu_1324_p2[0:0] === 1'b1) ? add_ln700_8_fu_1309_p2 : add_ln701_8_fu_1330_p2);

assign select_ln891_15_fu_1537_p3 = ((icmp_ln891_8_reg_1784[0:0] === 1'b1) ? select_ln891_13_fu_1520_p3 : tmp_18_fu_1527_p4);

assign select_ln891_16_fu_1381_p3 = ((icmp_ln891_9_fu_1369_p2[0:0] === 1'b1) ? add_ln700_9_fu_1354_p2 : add_ln701_9_fu_1375_p2);

assign select_ln891_1_fu_1412_p3 = ((icmp_ln891_1_reg_1749[0:0] === 1'b1) ? zext_ln700_fu_1400_p1 : tmp_2_fu_1404_p3);

assign select_ln891_2_fu_1066_p3 = ((icmp_ln891_2_fu_1054_p2[0:0] === 1'b1) ? add_ln700_2_fu_1039_p2 : add_ln701_2_fu_1060_p2);

assign select_ln891_3_fu_1435_p3 = ((icmp_ln891_2_reg_1754[0:0] === 1'b1) ? zext_ln891_fu_1419_p1 : zext_ln816_fu_1431_p1);

assign select_ln891_4_fu_1111_p3 = ((icmp_ln891_3_fu_1099_p2[0:0] === 1'b1) ? add_ln700_3_fu_1084_p2 : add_ln701_3_fu_1105_p2);

assign select_ln891_5_fu_1452_p3 = ((icmp_ln891_3_reg_1759[0:0] === 1'b1) ? select_ln891_3_fu_1435_p3 : tmp_8_fu_1442_p4);

assign select_ln891_6_fu_1156_p3 = ((icmp_ln891_4_fu_1144_p2[0:0] === 1'b1) ? add_ln700_4_fu_1129_p2 : add_ln701_4_fu_1150_p2);

assign select_ln891_7_fu_1469_p3 = ((icmp_ln891_4_reg_1764[0:0] === 1'b1) ? select_ln891_5_fu_1452_p3 : tmp_10_fu_1459_p4);

assign select_ln891_8_fu_1201_p3 = ((icmp_ln891_5_fu_1189_p2[0:0] === 1'b1) ? add_ln700_5_fu_1174_p2 : add_ln701_5_fu_1195_p2);

assign select_ln891_9_fu_1486_p3 = ((icmp_ln891_5_reg_1769[0:0] === 1'b1) ? select_ln891_7_fu_1469_p3 : tmp_12_fu_1476_p4);

assign select_ln891_fu_1021_p3 = ((icmp_ln891_1_fu_1009_p2[0:0] === 1'b1) ? add_ln700_1_fu_994_p2 : add_ln701_1_fu_1015_p2);

assign sext_ln68_1_fu_775_p1 = $signed(W_FC_V_1_q0);

assign sext_ln68_2_fu_785_p1 = $signed(W_FC_V_2_q0);

assign sext_ln68_3_fu_795_p1 = $signed(W_FC_V_3_q0);

assign sext_ln68_4_fu_805_p1 = $signed(W_FC_V_4_q0);

assign sext_ln68_5_fu_815_p1 = $signed(W_FC_V_5_q0);

assign sext_ln68_6_fu_825_p1 = $signed(W_FC_V_6_q0);

assign sext_ln68_7_fu_835_p1 = $signed(W_FC_V_7_q0);

assign sext_ln68_8_fu_845_p1 = $signed(W_FC_V_8_q0);

assign sext_ln68_9_fu_855_p1 = $signed(W_FC_V_9_q0);

assign sext_ln68_fu_765_p1 = $signed(W_FC_V_0_q0);

assign shl_ln791_fu_747_p2 = 32'd1 << zext_ln64_fu_741_p1;

always @ (*) begin
    tmp_10_fu_1459_p4 = select_ln891_5_fu_1452_p3;
    tmp_10_fu_1459_p4[32'd4] = |(1'd1);
end

assign tmp_11_fu_1179_p4 = {{add_ln700_5_fu_1174_p2[31:8]}};

always @ (*) begin
    tmp_12_fu_1476_p4 = select_ln891_7_fu_1469_p3;
    tmp_12_fu_1476_p4[32'd5] = |(1'd1);
end

assign tmp_13_fu_1224_p4 = {{add_ln700_6_fu_1219_p2[31:8]}};

always @ (*) begin
    tmp_14_fu_1493_p4 = select_ln891_9_fu_1486_p3;
    tmp_14_fu_1493_p4[32'd6] = |(1'd1);
end

assign tmp_15_fu_1269_p4 = {{add_ln700_7_fu_1264_p2[31:8]}};

always @ (*) begin
    tmp_16_fu_1510_p4 = select_ln891_11_fu_1503_p3;
    tmp_16_fu_1510_p4[32'd7] = |(1'd1);
end

assign tmp_17_fu_1314_p4 = {{add_ln700_8_fu_1309_p2[31:8]}};

always @ (*) begin
    tmp_18_fu_1527_p4 = select_ln891_13_fu_1520_p3;
    tmp_18_fu_1527_p4[32'd8] = |(1'd1);
end

assign tmp_19_fu_1359_p4 = {{add_ln700_9_fu_1354_p2[31:8]}};

always @ (*) begin
    tmp_20_fu_1544_p4 = select_ln891_15_fu_1537_p3;
    tmp_20_fu_1544_p4[32'd9] = |(1'd1);
end

assign tmp_2_fu_1404_p3 = {{1'd1}, {xor_ln85_fu_1395_p2}};

assign tmp_3_fu_954_p4 = {{add_ln700_fu_949_p2[31:8]}};

assign tmp_4_fu_999_p4 = {{add_ln700_1_fu_994_p2[31:8]}};

assign tmp_5_fu_1044_p4 = {{add_ln700_2_fu_1039_p2[31:8]}};

assign tmp_6_fu_1423_p3 = {{1'd1}, {select_ln891_1_fu_1412_p3}};

assign tmp_7_fu_1089_p4 = {{add_ln700_3_fu_1084_p2[31:8]}};

always @ (*) begin
    tmp_8_fu_1442_p4 = select_ln891_3_fu_1435_p3;
    tmp_8_fu_1442_p4[32'd3] = |(1'd1);
end

assign tmp_9_fu_1134_p4 = {{add_ln700_4_fu_1129_p2[31:8]}};

assign tmp_fu_549_p3 = {{n_steps}, {12'd0}};

assign xor_ln85_fu_1395_p2 = (icmp_ln891_reg_1744 ^ 1'd1);

assign y_last_V_fu_666_p2 = ((zext_ln43_fu_612_p1 == add_ln96_reg_1574) ? 1'b1 : 1'b0);

assign zext_ln43_fu_612_p1 = select_ln43_12_fu_604_p3;

assign zext_ln64_fu_741_p1 = bvh_d_index_reg_1612;

assign zext_ln700_fu_1400_p1 = xor_ln85_fu_1395_p2;

assign zext_ln73_fu_640_p1 = select_ln43_11_fu_590_p3;

assign zext_ln816_fu_1431_p1 = tmp_6_fu_1423_p3;

assign zext_ln891_fu_1419_p1 = select_ln891_1_fu_1412_p3;

always @ (posedge ap_clk) begin
    tmp_reg_1579[11:0] <= 12'b000000000000;
end

endmodule //fc_snn_top
