-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fc_snn_top is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of fc_snn_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fc_snn_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.534500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=1488,HLS_SYN_LUT=3626,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv44_0 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv44_1 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000001";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv32_FFFFFF00 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111100000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal n_steps : STD_LOGIC_VECTOR (31 downto 0);
    signal clear_state : STD_LOGIC;
    signal v_mem_V_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal v_mem_V_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal W_FC_V_0_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_0_ce0 : STD_LOGIC;
    signal W_FC_V_0_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_1_ce0 : STD_LOGIC;
    signal W_FC_V_1_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_2_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_2_ce0 : STD_LOGIC;
    signal W_FC_V_2_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_3_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_3_ce0 : STD_LOGIC;
    signal W_FC_V_3_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_4_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_4_ce0 : STD_LOGIC;
    signal W_FC_V_4_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_5_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_5_ce0 : STD_LOGIC;
    signal W_FC_V_5_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_6_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_6_ce0 : STD_LOGIC;
    signal W_FC_V_6_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal W_FC_V_7_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_7_ce0 : STD_LOGIC;
    signal W_FC_V_7_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal W_FC_V_8_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_8_ce0 : STD_LOGIC;
    signal W_FC_V_8_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal W_FC_V_9_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal W_FC_V_9_ce0 : STD_LOGIC;
    signal W_FC_V_9_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln43_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal icmp_ln60_1_reg_1675 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_1_reg_1675_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal icmp_ln60_1_reg_1675_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_330 : STD_LOGIC_VECTOR (43 downto 0);
    signal t_0_reg_341 : STD_LOGIC_VECTOR (30 downto 0);
    signal acc_V_9_0_reg_352 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_8_0_reg_364 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_7_0_reg_376 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_6_0_reg_388 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_5_0_reg_400 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_4_0_reg_412 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_3_0_reg_424 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_2_0_reg_436 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_1_0_reg_448 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_0_0_reg_460 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_472 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln96_fu_543_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln96_reg_1574 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_549_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_reg_1579 : STD_LOGIC_VECTOR (43 downto 0);
    signal icmp_ln43_reg_1584 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op71_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln43_reg_1584_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln43_fu_567_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal icmp_ln60_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_1593 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_12_fu_604_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln43_12_reg_1607 : STD_LOGIC_VECTOR (30 downto 0);
    signal bvh_d_index_fu_616_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal bvh_d_index_reg_1612 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_654_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal i_reg_1670 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln60_1_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_1_reg_1675_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_V_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_V_reg_1679 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_V_reg_1679_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal y_last_V_reg_1679_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_9_V_1_fu_865_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_9_V_1_reg_1684 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal acc_8_V_1_fu_873_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_8_V_1_reg_1690 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_7_V_1_fu_881_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_7_V_1_reg_1696 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_6_V_1_fu_889_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_6_V_1_reg_1702 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_5_V_1_fu_897_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_5_V_1_reg_1708 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_V_1_fu_905_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_V_1_reg_1714 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_V_1_fu_913_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_V_1_reg_1720 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_V_1_fu_921_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_V_1_reg_1726 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_V_1_fu_929_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_V_1_reg_1732 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_0_V_1_fu_937_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_0_V_1_reg_1738 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln891_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_reg_1744 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_1_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_1_reg_1749 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_2_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_2_reg_1754 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_3_fu_1099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_3_reg_1759 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_4_fu_1144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_4_reg_1764 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_5_fu_1189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_5_reg_1769 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_6_fu_1234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_6_reg_1774 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_7_fu_1279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_7_reg_1779 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_8_fu_1324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_8_reg_1784 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_9_fu_1369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln891_9_reg_1789 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_phi_mux_t_0_phi_fu_345_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_acc_V_9_0_phi_fu_356_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_8_0_phi_fu_368_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_7_0_phi_fu_380_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_6_0_phi_fu_392_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_5_0_phi_fu_404_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_4_0_phi_fu_416_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_3_0_phi_fu_428_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_2_0_phi_fu_440_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_1_0_phi_fu_452_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_acc_V_0_0_phi_fu_464_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_i_0_phi_fu_476_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln73_fu_640_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal clear_state_read_read_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln85_fu_976_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_fu_1021_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_2_fu_1066_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_4_fu_1111_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_6_fu_1156_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_8_fu_1201_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_10_fu_1246_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_12_fu_1291_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_14_fu_1336_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_16_fu_1381_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_s_fu_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_10_fu_582_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln43_1_fu_598_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln43_11_fu_590_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln43_fu_612_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln64_fu_741_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln791_fu_747_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln791_fu_753_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_9_fu_734_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_fu_765_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_8_fu_727_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_1_fu_775_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_7_fu_720_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_2_fu_785_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_6_fu_713_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_3_fu_795_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_5_fu_706_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_4_fu_805_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_4_fu_699_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_5_fu_815_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_3_fu_692_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_6_fu_825_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_2_fu_685_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_7_fu_835_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_1_fu_678_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_8_fu_845_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_fu_671_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln68_9_fu_855_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_9_V_fu_859_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_8_V_fu_849_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_7_V_fu_839_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_6_V_fu_829_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_5_V_fu_819_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_4_V_fu_809_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_V_fu_799_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_V_fu_789_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_V_fu_779_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_0_V_fu_769_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_fu_949_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_954_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_fu_970_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_1_fu_994_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_999_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_1_fu_1015_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_2_fu_1039_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_1044_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_2_fu_1060_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_3_fu_1084_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_1089_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_3_fu_1105_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_4_fu_1129_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_1134_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_4_fu_1150_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_5_fu_1174_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_1179_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_5_fu_1195_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_6_fu_1219_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1224_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_6_fu_1240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_7_fu_1264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_1269_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_7_fu_1285_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_8_fu_1309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_1314_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_8_fu_1330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln700_9_fu_1354_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_1359_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln701_9_fu_1375_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln85_fu_1395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln700_fu_1400_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1404_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln891_1_fu_1412_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_1423_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln891_fu_1419_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln816_fu_1431_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_3_fu_1435_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_1442_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_5_fu_1452_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_1459_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_7_fu_1469_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_1476_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_9_fu_1486_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_1493_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_11_fu_1503_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_1510_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_13_fu_1520_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_1527_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln891_15_fu_1537_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_1544_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int : STD_LOGIC;
    signal in_stream_TREADY_int : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int : STD_LOGIC;
    signal out_stream_TREADY_int : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;

    component fc_snn_top_W_FC_V_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_3 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_4 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_5 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_6 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_7 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_8 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component fc_snn_top_W_FC_V_9 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component fc_snn_top_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        n_steps : OUT STD_LOGIC_VECTOR (31 downto 0);
        clear_state : OUT STD_LOGIC );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    W_FC_V_0_U : component fc_snn_top_W_FC_V_0
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_0_address0,
        ce0 => W_FC_V_0_ce0,
        q0 => W_FC_V_0_q0);

    W_FC_V_1_U : component fc_snn_top_W_FC_V_1
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_1_address0,
        ce0 => W_FC_V_1_ce0,
        q0 => W_FC_V_1_q0);

    W_FC_V_2_U : component fc_snn_top_W_FC_V_2
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_2_address0,
        ce0 => W_FC_V_2_ce0,
        q0 => W_FC_V_2_q0);

    W_FC_V_3_U : component fc_snn_top_W_FC_V_3
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_3_address0,
        ce0 => W_FC_V_3_ce0,
        q0 => W_FC_V_3_q0);

    W_FC_V_4_U : component fc_snn_top_W_FC_V_4
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_4_address0,
        ce0 => W_FC_V_4_ce0,
        q0 => W_FC_V_4_q0);

    W_FC_V_5_U : component fc_snn_top_W_FC_V_5
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_5_address0,
        ce0 => W_FC_V_5_ce0,
        q0 => W_FC_V_5_q0);

    W_FC_V_6_U : component fc_snn_top_W_FC_V_6
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_6_address0,
        ce0 => W_FC_V_6_ce0,
        q0 => W_FC_V_6_q0);

    W_FC_V_7_U : component fc_snn_top_W_FC_V_7
    generic map (
        DataWidth => 7,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_7_address0,
        ce0 => W_FC_V_7_ce0,
        q0 => W_FC_V_7_q0);

    W_FC_V_8_U : component fc_snn_top_W_FC_V_8
    generic map (
        DataWidth => 7,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_8_address0,
        ce0 => W_FC_V_8_ce0,
        q0 => W_FC_V_8_q0);

    W_FC_V_9_U : component fc_snn_top_W_FC_V_9
    generic map (
        DataWidth => 6,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => W_FC_V_9_address0,
        ce0 => W_FC_V_9_ce0,
        q0 => W_FC_V_9_q0);

    fc_snn_top_CTRL_s_axi_U : component fc_snn_top_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        n_steps => n_steps,
        clear_state => clear_state);

    regslice_both_in_stream_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int,
        vld_out => in_stream_TVALID_int,
        ack_out => in_stream_TREADY_int,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int,
        vld_in => out_stream_TVALID_int,
        ack_in => out_stream_TREADY_int,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y_last_V_reg_1679_pp0_iter2_reg,
        vld_in => out_stream_TVALID_int,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    acc_V_0_0_reg_460_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_0_0_reg_460 <= acc_0_V_1_reg_1738;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_0_0_reg_460 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_1_0_reg_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_1_0_reg_448 <= acc_1_V_1_reg_1732;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_1_0_reg_448 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_2_0_reg_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_2_0_reg_436 <= acc_2_V_1_reg_1726;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_2_0_reg_436 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_3_0_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_3_0_reg_424 <= acc_3_V_1_reg_1720;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_3_0_reg_424 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_4_0_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_4_0_reg_412 <= acc_4_V_1_reg_1714;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_4_0_reg_412 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_5_0_reg_400_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_5_0_reg_400 <= acc_5_V_1_reg_1708;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_5_0_reg_400 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_6_0_reg_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_6_0_reg_388 <= acc_6_V_1_reg_1702;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_6_0_reg_388 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_7_0_reg_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_7_0_reg_376 <= acc_7_V_1_reg_1696;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_7_0_reg_376 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_8_0_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_8_0_reg_364 <= acc_8_V_1_reg_1690;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_8_0_reg_364 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_V_9_0_reg_352_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0))) then 
                acc_V_9_0_reg_352 <= acc_9_V_1_reg_1684;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                acc_V_9_0_reg_352 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_reg_472_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_reg_1584 = ap_const_lv1_0))) then 
                i_0_reg_472 <= i_reg_1670;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_472 <= ap_const_lv13_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_330_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_330 <= add_ln43_fu_567_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_reg_330 <= ap_const_lv44_0;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln64_fu_620_p2 = ap_const_lv1_1) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0))) then 
                p_Val2_s_fu_154 <= in_stream_TDATA_int;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln64_fu_620_p2 = ap_const_lv1_0) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0))) then 
                p_Val2_s_fu_154 <= select_ln43_10_fu_582_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                p_Val2_s_fu_154 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_0_reg_341_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_reg_1584 = ap_const_lv1_0))) then 
                t_0_reg_341 <= select_ln43_12_reg_1607;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                t_0_reg_341 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    v_mem_V_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_0 <= select_ln85_fu_976_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_0 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_1 <= select_ln891_fu_1021_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_1 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_2 <= select_ln891_2_fu_1066_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_2 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_3 <= select_ln891_4_fu_1111_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_3 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_4 <= select_ln891_6_fu_1156_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_4 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_5_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_5 <= select_ln891_8_fu_1201_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_5 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_6_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_6 <= select_ln891_10_fu_1246_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_6 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_7_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_7 <= select_ln891_12_fu_1291_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_7 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_8_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_8 <= select_ln891_14_fu_1336_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_8 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    v_mem_V_9_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then 
                v_mem_V_9 <= select_ln891_16_fu_1381_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (clear_state_read_read_fu_158_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1))) then 
                v_mem_V_9 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_reg_1584 = ap_const_lv1_0))) then
                acc_0_V_1_reg_1738 <= acc_0_V_1_fu_937_p3;
                acc_1_V_1_reg_1732 <= acc_1_V_1_fu_929_p3;
                acc_2_V_1_reg_1726 <= acc_2_V_1_fu_921_p3;
                acc_3_V_1_reg_1720 <= acc_3_V_1_fu_913_p3;
                acc_4_V_1_reg_1714 <= acc_4_V_1_fu_905_p3;
                acc_5_V_1_reg_1708 <= acc_5_V_1_fu_897_p3;
                acc_6_V_1_reg_1702 <= acc_6_V_1_fu_889_p3;
                acc_7_V_1_reg_1696 <= acc_7_V_1_fu_881_p3;
                acc_8_V_1_reg_1690 <= acc_8_V_1_fu_873_p3;
                acc_9_V_1_reg_1684 <= acc_9_V_1_fu_865_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                add_ln96_reg_1574 <= add_ln96_fu_543_p2;
                    tmp_reg_1579(43 downto 12) <= tmp_fu_549_p3(43 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0))) then
                bvh_d_index_reg_1612 <= bvh_d_index_fu_616_p1;
                icmp_ln60_1_reg_1675 <= icmp_ln60_1_fu_660_p2;
                icmp_ln60_reg_1593 <= icmp_ln60_fu_576_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0))) then
                i_reg_1670 <= i_fu_654_p2;
                select_ln43_12_reg_1607 <= select_ln43_12_fu_604_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln43_reg_1584 <= icmp_ln43_fu_562_p2;
                icmp_ln43_reg_1584_pp0_iter1_reg <= icmp_ln43_reg_1584;
                icmp_ln60_1_reg_1675_pp0_iter1_reg <= icmp_ln60_1_reg_1675;
                y_last_V_reg_1679_pp0_iter1_reg <= y_last_V_reg_1679;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln60_1_reg_1675_pp0_iter2_reg <= icmp_ln60_1_reg_1675_pp0_iter1_reg;
                icmp_ln60_1_reg_1675_pp0_iter3_reg <= icmp_ln60_1_reg_1675_pp0_iter2_reg;
                y_last_V_reg_1679_pp0_iter2_reg <= y_last_V_reg_1679_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln60_1_reg_1675_pp0_iter1_reg = ap_const_lv1_1))) then
                icmp_ln891_1_reg_1749 <= icmp_ln891_1_fu_1009_p2;
                icmp_ln891_2_reg_1754 <= icmp_ln891_2_fu_1054_p2;
                icmp_ln891_3_reg_1759 <= icmp_ln891_3_fu_1099_p2;
                icmp_ln891_4_reg_1764 <= icmp_ln891_4_fu_1144_p2;
                icmp_ln891_5_reg_1769 <= icmp_ln891_5_fu_1189_p2;
                icmp_ln891_6_reg_1774 <= icmp_ln891_6_fu_1234_p2;
                icmp_ln891_7_reg_1779 <= icmp_ln891_7_fu_1279_p2;
                icmp_ln891_8_reg_1784 <= icmp_ln891_8_fu_1324_p2;
                icmp_ln891_9_reg_1789 <= icmp_ln891_9_fu_1369_p2;
                icmp_ln891_reg_1744 <= icmp_ln891_fu_964_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln60_1_fu_660_p2 = ap_const_lv1_1) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0))) then
                y_last_V_reg_1679 <= y_last_V_fu_666_p2;
            end if;
        end if;
    end process;
    tmp_reg_1579(11 downto 0) <= "000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln43_fu_562_p2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_CS_fsm_state7, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln43_fu_562_p2 = ap_const_lv1_1))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln43_fu_562_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    W_FC_V_0_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_0_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_1_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_1_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_2_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_2_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_3_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_3_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_4_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_4_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_5_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_5_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_6_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_6_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_7_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_7_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_8_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_8_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_FC_V_9_address0 <= zext_ln73_fu_640_p1(12 - 1 downto 0);

    W_FC_V_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            W_FC_V_9_ce0 <= ap_const_logic_1;
        else 
            W_FC_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_0_V_1_fu_937_p3 <= 
        select_ln43_9_fu_734_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_0_V_fu_769_p2;
    acc_0_V_fu_769_p2 <= std_logic_vector(unsigned(select_ln43_9_fu_734_p3) + unsigned(sext_ln68_fu_765_p1));
    acc_1_V_1_fu_929_p3 <= 
        select_ln43_8_fu_727_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_1_V_fu_779_p2;
    acc_1_V_fu_779_p2 <= std_logic_vector(unsigned(select_ln43_8_fu_727_p3) + unsigned(sext_ln68_1_fu_775_p1));
    acc_2_V_1_fu_921_p3 <= 
        select_ln43_7_fu_720_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_2_V_fu_789_p2;
    acc_2_V_fu_789_p2 <= std_logic_vector(unsigned(select_ln43_7_fu_720_p3) + unsigned(sext_ln68_2_fu_785_p1));
    acc_3_V_1_fu_913_p3 <= 
        select_ln43_6_fu_713_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_3_V_fu_799_p2;
    acc_3_V_fu_799_p2 <= std_logic_vector(unsigned(select_ln43_6_fu_713_p3) + unsigned(sext_ln68_3_fu_795_p1));
    acc_4_V_1_fu_905_p3 <= 
        select_ln43_5_fu_706_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_4_V_fu_809_p2;
    acc_4_V_fu_809_p2 <= std_logic_vector(unsigned(select_ln43_5_fu_706_p3) + unsigned(sext_ln68_4_fu_805_p1));
    acc_5_V_1_fu_897_p3 <= 
        select_ln43_4_fu_699_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_5_V_fu_819_p2;
    acc_5_V_fu_819_p2 <= std_logic_vector(unsigned(select_ln43_4_fu_699_p3) + unsigned(sext_ln68_5_fu_815_p1));
    acc_6_V_1_fu_889_p3 <= 
        select_ln43_3_fu_692_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_6_V_fu_829_p2;
    acc_6_V_fu_829_p2 <= std_logic_vector(unsigned(select_ln43_3_fu_692_p3) + unsigned(sext_ln68_6_fu_825_p1));
    acc_7_V_1_fu_881_p3 <= 
        select_ln43_2_fu_685_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_7_V_fu_839_p2;
    acc_7_V_fu_839_p2 <= std_logic_vector(unsigned(select_ln43_2_fu_685_p3) + unsigned(sext_ln68_7_fu_835_p1));
    acc_8_V_1_fu_873_p3 <= 
        select_ln43_1_fu_678_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_8_V_fu_849_p2;
    acc_8_V_fu_849_p2 <= std_logic_vector(unsigned(select_ln43_1_fu_678_p3) + unsigned(sext_ln68_8_fu_845_p1));
    acc_9_V_1_fu_865_p3 <= 
        select_ln43_fu_671_p3 when (p_Result_s_fu_759_p2(0) = '1') else 
        acc_9_V_fu_859_p2;
    acc_9_V_fu_859_p2 <= std_logic_vector(unsigned(select_ln43_fu_671_p3) + unsigned(sext_ln68_9_fu_855_p1));
    add_ln43_1_fu_598_p2 <= std_logic_vector(unsigned(ap_const_lv31_1) + unsigned(ap_phi_mux_t_0_phi_fu_345_p4));
    add_ln43_fu_567_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_330) + unsigned(ap_const_lv44_1));
    add_ln700_1_fu_994_p2 <= std_logic_vector(unsigned(v_mem_V_1) + unsigned(acc_1_V_1_reg_1732));
    add_ln700_2_fu_1039_p2 <= std_logic_vector(unsigned(v_mem_V_2) + unsigned(acc_2_V_1_reg_1726));
    add_ln700_3_fu_1084_p2 <= std_logic_vector(unsigned(v_mem_V_3) + unsigned(acc_3_V_1_reg_1720));
    add_ln700_4_fu_1129_p2 <= std_logic_vector(unsigned(v_mem_V_4) + unsigned(acc_4_V_1_reg_1714));
    add_ln700_5_fu_1174_p2 <= std_logic_vector(unsigned(v_mem_V_5) + unsigned(acc_5_V_1_reg_1708));
    add_ln700_6_fu_1219_p2 <= std_logic_vector(unsigned(v_mem_V_6) + unsigned(acc_6_V_1_reg_1702));
    add_ln700_7_fu_1264_p2 <= std_logic_vector(unsigned(v_mem_V_7) + unsigned(acc_7_V_1_reg_1696));
    add_ln700_8_fu_1309_p2 <= std_logic_vector(unsigned(v_mem_V_8) + unsigned(acc_8_V_1_reg_1690));
    add_ln700_9_fu_1354_p2 <= std_logic_vector(unsigned(v_mem_V_9) + unsigned(acc_9_V_1_reg_1684));
    add_ln700_fu_949_p2 <= std_logic_vector(unsigned(v_mem_V_0) + unsigned(acc_0_V_1_reg_1738));
    add_ln701_1_fu_1015_p2 <= std_logic_vector(unsigned(add_ln700_1_fu_994_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_2_fu_1060_p2 <= std_logic_vector(unsigned(add_ln700_2_fu_1039_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_3_fu_1105_p2 <= std_logic_vector(unsigned(add_ln700_3_fu_1084_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_4_fu_1150_p2 <= std_logic_vector(unsigned(add_ln700_4_fu_1129_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_5_fu_1195_p2 <= std_logic_vector(unsigned(add_ln700_5_fu_1174_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_6_fu_1240_p2 <= std_logic_vector(unsigned(add_ln700_6_fu_1219_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_7_fu_1285_p2 <= std_logic_vector(unsigned(add_ln700_7_fu_1264_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_8_fu_1330_p2 <= std_logic_vector(unsigned(add_ln700_8_fu_1309_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_9_fu_1375_p2 <= std_logic_vector(unsigned(add_ln700_9_fu_1354_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln701_fu_970_p2 <= std_logic_vector(unsigned(add_ln700_fu_949_p2) + unsigned(ap_const_lv32_FFFFFF00));
    add_ln96_fu_543_p2 <= std_logic_vector(unsigned(n_steps) + unsigned(ap_const_lv32_FFFFFFFF));
    and_ln791_fu_753_p2 <= (shl_ln791_fu_747_p2 and p_Val2_s_fu_154);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state7 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_predicate_op71_read_state2, in_stream_TVALID_int)
    begin
                ap_block_pp0_stage0_01001 <= ((in_stream_TVALID_int = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_predicate_op71_read_state2, ap_block_state5_io, ap_block_state6_io, in_stream_TVALID_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((in_stream_TVALID_int = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_predicate_op71_read_state2, ap_block_state5_io, ap_block_state6_io, in_stream_TVALID_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((in_stream_TVALID_int = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(ap_predicate_op71_read_state2, in_stream_TVALID_int)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((in_stream_TVALID_int = ap_const_logic_0) and (ap_predicate_op71_read_state2 = ap_const_boolean_1));
    end process;

        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_io_assign_proc : process(icmp_ln60_1_reg_1675_pp0_iter2_reg, out_stream_TREADY_int)
    begin
                ap_block_state5_io <= ((out_stream_TREADY_int = ap_const_logic_0) and (icmp_ln60_1_reg_1675_pp0_iter2_reg = ap_const_lv1_1));
    end process;

        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(icmp_ln60_1_reg_1675_pp0_iter3_reg, out_stream_TREADY_int)
    begin
                ap_block_state6_io <= ((out_stream_TREADY_int = ap_const_logic_0) and (icmp_ln60_1_reg_1675_pp0_iter3_reg = ap_const_lv1_1));
    end process;

        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln43_fu_562_p2)
    begin
        if ((icmp_ln43_fu_562_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state7, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_acc_V_0_0_phi_fu_464_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_0_0_reg_460, icmp_ln43_reg_1584_pp0_iter1_reg, acc_0_V_1_reg_1738, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_0_0_phi_fu_464_p4 <= acc_0_V_1_reg_1738;
        else 
            ap_phi_mux_acc_V_0_0_phi_fu_464_p4 <= acc_V_0_0_reg_460;
        end if; 
    end process;


    ap_phi_mux_acc_V_1_0_phi_fu_452_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_1_0_reg_448, icmp_ln43_reg_1584_pp0_iter1_reg, acc_1_V_1_reg_1732, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_1_0_phi_fu_452_p4 <= acc_1_V_1_reg_1732;
        else 
            ap_phi_mux_acc_V_1_0_phi_fu_452_p4 <= acc_V_1_0_reg_448;
        end if; 
    end process;


    ap_phi_mux_acc_V_2_0_phi_fu_440_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_2_0_reg_436, icmp_ln43_reg_1584_pp0_iter1_reg, acc_2_V_1_reg_1726, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_2_0_phi_fu_440_p4 <= acc_2_V_1_reg_1726;
        else 
            ap_phi_mux_acc_V_2_0_phi_fu_440_p4 <= acc_V_2_0_reg_436;
        end if; 
    end process;


    ap_phi_mux_acc_V_3_0_phi_fu_428_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_3_0_reg_424, icmp_ln43_reg_1584_pp0_iter1_reg, acc_3_V_1_reg_1720, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_3_0_phi_fu_428_p4 <= acc_3_V_1_reg_1720;
        else 
            ap_phi_mux_acc_V_3_0_phi_fu_428_p4 <= acc_V_3_0_reg_424;
        end if; 
    end process;


    ap_phi_mux_acc_V_4_0_phi_fu_416_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_4_0_reg_412, icmp_ln43_reg_1584_pp0_iter1_reg, acc_4_V_1_reg_1714, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_4_0_phi_fu_416_p4 <= acc_4_V_1_reg_1714;
        else 
            ap_phi_mux_acc_V_4_0_phi_fu_416_p4 <= acc_V_4_0_reg_412;
        end if; 
    end process;


    ap_phi_mux_acc_V_5_0_phi_fu_404_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_5_0_reg_400, icmp_ln43_reg_1584_pp0_iter1_reg, acc_5_V_1_reg_1708, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_5_0_phi_fu_404_p4 <= acc_5_V_1_reg_1708;
        else 
            ap_phi_mux_acc_V_5_0_phi_fu_404_p4 <= acc_V_5_0_reg_400;
        end if; 
    end process;


    ap_phi_mux_acc_V_6_0_phi_fu_392_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_6_0_reg_388, icmp_ln43_reg_1584_pp0_iter1_reg, acc_6_V_1_reg_1702, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_6_0_phi_fu_392_p4 <= acc_6_V_1_reg_1702;
        else 
            ap_phi_mux_acc_V_6_0_phi_fu_392_p4 <= acc_V_6_0_reg_388;
        end if; 
    end process;


    ap_phi_mux_acc_V_7_0_phi_fu_380_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_7_0_reg_376, icmp_ln43_reg_1584_pp0_iter1_reg, acc_7_V_1_reg_1696, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_7_0_phi_fu_380_p4 <= acc_7_V_1_reg_1696;
        else 
            ap_phi_mux_acc_V_7_0_phi_fu_380_p4 <= acc_V_7_0_reg_376;
        end if; 
    end process;


    ap_phi_mux_acc_V_8_0_phi_fu_368_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_8_0_reg_364, icmp_ln43_reg_1584_pp0_iter1_reg, acc_8_V_1_reg_1690, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_8_0_phi_fu_368_p4 <= acc_8_V_1_reg_1690;
        else 
            ap_phi_mux_acc_V_8_0_phi_fu_368_p4 <= acc_V_8_0_reg_364;
        end if; 
    end process;


    ap_phi_mux_acc_V_9_0_phi_fu_356_p4_assign_proc : process(ap_block_pp0_stage0, acc_V_9_0_reg_352, icmp_ln43_reg_1584_pp0_iter1_reg, acc_9_V_1_reg_1684, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln43_reg_1584_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_acc_V_9_0_phi_fu_356_p4 <= acc_9_V_1_reg_1684;
        else 
            ap_phi_mux_acc_V_9_0_phi_fu_356_p4 <= acc_V_9_0_reg_352;
        end if; 
    end process;


    ap_phi_mux_i_0_phi_fu_476_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_0_reg_472, icmp_ln43_reg_1584, i_reg_1670, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_reg_1584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_i_0_phi_fu_476_p4 <= i_reg_1670;
        else 
            ap_phi_mux_i_0_phi_fu_476_p4 <= i_0_reg_472;
        end if; 
    end process;


    ap_phi_mux_t_0_phi_fu_345_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, t_0_reg_341, icmp_ln43_reg_1584, select_ln43_12_reg_1607, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln43_reg_1584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_t_0_phi_fu_345_p4 <= select_ln43_12_reg_1607;
        else 
            ap_phi_mux_t_0_phi_fu_345_p4 <= t_0_reg_341;
        end if; 
    end process;


    ap_predicate_op71_read_state2_assign_proc : process(icmp_ln43_fu_562_p2, icmp_ln64_fu_620_p2)
    begin
                ap_predicate_op71_read_state2 <= ((icmp_ln64_fu_620_p2 = ap_const_lv1_1) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bvh_d_index_fu_616_p1 <= select_ln43_11_fu_590_p3(5 - 1 downto 0);
    clear_state_read_read_fu_158_p2 <= (0=>clear_state, others=>'-');
    i_fu_654_p2 <= std_logic_vector(unsigned(select_ln43_11_fu_590_p3) + unsigned(ap_const_lv13_1));
    icmp_ln43_fu_562_p2 <= "1" when (indvar_flatten_reg_330 = tmp_reg_1579) else "0";
    icmp_ln60_1_fu_660_p2 <= "1" when (i_fu_654_p2 = ap_const_lv13_1000) else "0";
    icmp_ln60_fu_576_p2 <= "1" when (ap_phi_mux_i_0_phi_fu_476_p4 = ap_const_lv13_1000) else "0";
    icmp_ln64_fu_620_p2 <= "1" when (bvh_d_index_fu_616_p1 = ap_const_lv5_0) else "0";
    icmp_ln891_1_fu_1009_p2 <= "1" when (signed(tmp_4_fu_999_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_2_fu_1054_p2 <= "1" when (signed(tmp_5_fu_1044_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_3_fu_1099_p2 <= "1" when (signed(tmp_7_fu_1089_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_4_fu_1144_p2 <= "1" when (signed(tmp_9_fu_1134_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_5_fu_1189_p2 <= "1" when (signed(tmp_11_fu_1179_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_6_fu_1234_p2 <= "1" when (signed(tmp_13_fu_1224_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_7_fu_1279_p2 <= "1" when (signed(tmp_15_fu_1269_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_8_fu_1324_p2 <= "1" when (signed(tmp_17_fu_1314_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_9_fu_1369_p2 <= "1" when (signed(tmp_19_fu_1359_p4) < signed(ap_const_lv24_1)) else "0";
    icmp_ln891_fu_964_p2 <= "1" when (signed(tmp_3_fu_954_p4) < signed(ap_const_lv24_1)) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln43_fu_562_p2, icmp_ln64_fu_620_p2, in_stream_TVALID_int)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln64_fu_620_p2 = ap_const_lv1_1) and (icmp_ln43_fu_562_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(in_stream_TVALID, regslice_both_in_stream_V_data_V_U_ack_in)
    begin
        if (((in_stream_TVALID = ap_const_logic_1) and (regslice_both_in_stream_V_data_V_U_ack_in = ap_const_logic_1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_TREADY_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op71_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op71_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int <= ap_const_logic_1;
        else 
            in_stream_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    out_stream_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln60_1_reg_1675_pp0_iter2_reg, ap_enable_reg_pp0_iter4, icmp_ln60_1_reg_1675_pp0_iter3_reg, out_stream_TREADY_int)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int <= 
        select_ln891_15_fu_1537_p3 when (icmp_ln891_9_reg_1789(0) = '1') else 
        tmp_20_fu_1544_p4;
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln60_1_reg_1675_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln60_1_reg_1675_pp0_iter2_reg = ap_const_lv1_1))) then 
            out_stream_TVALID_int <= ap_const_logic_1;
        else 
            out_stream_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_s_fu_759_p2 <= "1" when (and_ln791_fu_753_p2 = ap_const_lv32_0) else "0";
    select_ln43_10_fu_582_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_fu_576_p2(0) = '1') else 
        p_Val2_s_fu_154;
    select_ln43_11_fu_590_p3 <= 
        ap_const_lv13_0 when (icmp_ln60_fu_576_p2(0) = '1') else 
        ap_phi_mux_i_0_phi_fu_476_p4;
    select_ln43_12_fu_604_p3 <= 
        add_ln43_1_fu_598_p2 when (icmp_ln60_fu_576_p2(0) = '1') else 
        ap_phi_mux_t_0_phi_fu_345_p4;
    select_ln43_1_fu_678_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_8_0_phi_fu_368_p4;
    select_ln43_2_fu_685_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_7_0_phi_fu_380_p4;
    select_ln43_3_fu_692_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_6_0_phi_fu_392_p4;
    select_ln43_4_fu_699_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_5_0_phi_fu_404_p4;
    select_ln43_5_fu_706_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_4_0_phi_fu_416_p4;
    select_ln43_6_fu_713_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_3_0_phi_fu_428_p4;
    select_ln43_7_fu_720_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_2_0_phi_fu_440_p4;
    select_ln43_8_fu_727_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_1_0_phi_fu_452_p4;
    select_ln43_9_fu_734_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_0_0_phi_fu_464_p4;
    select_ln43_fu_671_p3 <= 
        ap_const_lv32_0 when (icmp_ln60_reg_1593(0) = '1') else 
        ap_phi_mux_acc_V_9_0_phi_fu_356_p4;
    select_ln85_fu_976_p3 <= 
        add_ln700_fu_949_p2 when (icmp_ln891_fu_964_p2(0) = '1') else 
        add_ln701_fu_970_p2;
    select_ln891_10_fu_1246_p3 <= 
        add_ln700_6_fu_1219_p2 when (icmp_ln891_6_fu_1234_p2(0) = '1') else 
        add_ln701_6_fu_1240_p2;
    select_ln891_11_fu_1503_p3 <= 
        select_ln891_9_fu_1486_p3 when (icmp_ln891_6_reg_1774(0) = '1') else 
        tmp_14_fu_1493_p4;
    select_ln891_12_fu_1291_p3 <= 
        add_ln700_7_fu_1264_p2 when (icmp_ln891_7_fu_1279_p2(0) = '1') else 
        add_ln701_7_fu_1285_p2;
    select_ln891_13_fu_1520_p3 <= 
        select_ln891_11_fu_1503_p3 when (icmp_ln891_7_reg_1779(0) = '1') else 
        tmp_16_fu_1510_p4;
    select_ln891_14_fu_1336_p3 <= 
        add_ln700_8_fu_1309_p2 when (icmp_ln891_8_fu_1324_p2(0) = '1') else 
        add_ln701_8_fu_1330_p2;
    select_ln891_15_fu_1537_p3 <= 
        select_ln891_13_fu_1520_p3 when (icmp_ln891_8_reg_1784(0) = '1') else 
        tmp_18_fu_1527_p4;
    select_ln891_16_fu_1381_p3 <= 
        add_ln700_9_fu_1354_p2 when (icmp_ln891_9_fu_1369_p2(0) = '1') else 
        add_ln701_9_fu_1375_p2;
    select_ln891_1_fu_1412_p3 <= 
        zext_ln700_fu_1400_p1 when (icmp_ln891_1_reg_1749(0) = '1') else 
        tmp_2_fu_1404_p3;
    select_ln891_2_fu_1066_p3 <= 
        add_ln700_2_fu_1039_p2 when (icmp_ln891_2_fu_1054_p2(0) = '1') else 
        add_ln701_2_fu_1060_p2;
    select_ln891_3_fu_1435_p3 <= 
        zext_ln891_fu_1419_p1 when (icmp_ln891_2_reg_1754(0) = '1') else 
        zext_ln816_fu_1431_p1;
    select_ln891_4_fu_1111_p3 <= 
        add_ln700_3_fu_1084_p2 when (icmp_ln891_3_fu_1099_p2(0) = '1') else 
        add_ln701_3_fu_1105_p2;
    select_ln891_5_fu_1452_p3 <= 
        select_ln891_3_fu_1435_p3 when (icmp_ln891_3_reg_1759(0) = '1') else 
        tmp_8_fu_1442_p4;
    select_ln891_6_fu_1156_p3 <= 
        add_ln700_4_fu_1129_p2 when (icmp_ln891_4_fu_1144_p2(0) = '1') else 
        add_ln701_4_fu_1150_p2;
    select_ln891_7_fu_1469_p3 <= 
        select_ln891_5_fu_1452_p3 when (icmp_ln891_4_reg_1764(0) = '1') else 
        tmp_10_fu_1459_p4;
    select_ln891_8_fu_1201_p3 <= 
        add_ln700_5_fu_1174_p2 when (icmp_ln891_5_fu_1189_p2(0) = '1') else 
        add_ln701_5_fu_1195_p2;
    select_ln891_9_fu_1486_p3 <= 
        select_ln891_7_fu_1469_p3 when (icmp_ln891_5_reg_1769(0) = '1') else 
        tmp_12_fu_1476_p4;
    select_ln891_fu_1021_p3 <= 
        add_ln700_1_fu_994_p2 when (icmp_ln891_1_fu_1009_p2(0) = '1') else 
        add_ln701_1_fu_1015_p2;
        sext_ln68_1_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_1_q0),32));

        sext_ln68_2_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_2_q0),32));

        sext_ln68_3_fu_795_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_3_q0),32));

        sext_ln68_4_fu_805_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_4_q0),32));

        sext_ln68_5_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_5_q0),32));

        sext_ln68_6_fu_825_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_6_q0),32));

        sext_ln68_7_fu_835_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_7_q0),32));

        sext_ln68_8_fu_845_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_8_q0),32));

        sext_ln68_9_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_9_q0),32));

        sext_ln68_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(W_FC_V_0_q0),32));

    shl_ln791_fu_747_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & zext_ln64_fu_741_p1(31-1 downto 0)))));
    
    tmp_10_fu_1459_p4_proc : process(select_ln891_5_fu_1452_p3)
    begin
        tmp_10_fu_1459_p4 <= select_ln891_5_fu_1452_p3;
        tmp_10_fu_1459_p4(4) <= ap_const_lv1_1(0);
    end process;

    tmp_11_fu_1179_p4 <= add_ln700_5_fu_1174_p2(31 downto 8);
    
    tmp_12_fu_1476_p4_proc : process(select_ln891_7_fu_1469_p3)
    begin
        tmp_12_fu_1476_p4 <= select_ln891_7_fu_1469_p3;
        tmp_12_fu_1476_p4(5) <= ap_const_lv1_1(0);
    end process;

    tmp_13_fu_1224_p4 <= add_ln700_6_fu_1219_p2(31 downto 8);
    
    tmp_14_fu_1493_p4_proc : process(select_ln891_9_fu_1486_p3)
    begin
        tmp_14_fu_1493_p4 <= select_ln891_9_fu_1486_p3;
        tmp_14_fu_1493_p4(6) <= ap_const_lv1_1(0);
    end process;

    tmp_15_fu_1269_p4 <= add_ln700_7_fu_1264_p2(31 downto 8);
    
    tmp_16_fu_1510_p4_proc : process(select_ln891_11_fu_1503_p3)
    begin
        tmp_16_fu_1510_p4 <= select_ln891_11_fu_1503_p3;
        tmp_16_fu_1510_p4(7) <= ap_const_lv1_1(0);
    end process;

    tmp_17_fu_1314_p4 <= add_ln700_8_fu_1309_p2(31 downto 8);
    
    tmp_18_fu_1527_p4_proc : process(select_ln891_13_fu_1520_p3)
    begin
        tmp_18_fu_1527_p4 <= select_ln891_13_fu_1520_p3;
        tmp_18_fu_1527_p4(8) <= ap_const_lv1_1(0);
    end process;

    tmp_19_fu_1359_p4 <= add_ln700_9_fu_1354_p2(31 downto 8);
    
    tmp_20_fu_1544_p4_proc : process(select_ln891_15_fu_1537_p3)
    begin
        tmp_20_fu_1544_p4 <= select_ln891_15_fu_1537_p3;
        tmp_20_fu_1544_p4(9) <= ap_const_lv1_1(0);
    end process;

    tmp_2_fu_1404_p3 <= (ap_const_lv1_1 & xor_ln85_fu_1395_p2);
    tmp_3_fu_954_p4 <= add_ln700_fu_949_p2(31 downto 8);
    tmp_4_fu_999_p4 <= add_ln700_1_fu_994_p2(31 downto 8);
    tmp_5_fu_1044_p4 <= add_ln700_2_fu_1039_p2(31 downto 8);
    tmp_6_fu_1423_p3 <= (ap_const_lv1_1 & select_ln891_1_fu_1412_p3);
    tmp_7_fu_1089_p4 <= add_ln700_3_fu_1084_p2(31 downto 8);
    
    tmp_8_fu_1442_p4_proc : process(select_ln891_3_fu_1435_p3)
    begin
        tmp_8_fu_1442_p4 <= select_ln891_3_fu_1435_p3;
        tmp_8_fu_1442_p4(3) <= ap_const_lv1_1(0);
    end process;

    tmp_9_fu_1134_p4 <= add_ln700_4_fu_1129_p2(31 downto 8);
    tmp_fu_549_p3 <= (n_steps & ap_const_lv12_0);
    xor_ln85_fu_1395_p2 <= (icmp_ln891_reg_1744 xor ap_const_lv1_1);
    y_last_V_fu_666_p2 <= "1" when (zext_ln43_fu_612_p1 = add_ln96_reg_1574) else "0";
    zext_ln43_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_12_fu_604_p3),32));
    zext_ln64_fu_741_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_reg_1612),32));
    zext_ln700_fu_1400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln85_fu_1395_p2),2));
    zext_ln73_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_11_fu_590_p3),64));
    zext_ln816_fu_1431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_1423_p3),32));
    zext_ln891_fu_1419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln891_1_fu_1412_p3),32));
end behav;
