#########################################################################################################################

# V1.1
set_property IOSTANDARD LVCMOS33 [get_ports CAM_I2C_scl]
set_property IOSTANDARD LVCMOS33 [get_ports CAM_I2C_sda]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[23]}]
set_property PACKAGE_PIN R7 [get_ports CAM_I2C_scl]
set_property PACKAGE_PIN U7 [get_ports CAM_I2C_sda]
set_property PACKAGE_PIN D20 [get_ports {LCD_IF_pdata_out[23]}]
set_property PACKAGE_PIN C20 [get_ports {LCD_IF_pdata_out[19]}]



set_property IOSTANDARD LVCMOS33 [get_ports clk_from_pad]
set_property PACKAGE_PIN Y9 [get_ports clk_from_pad]


set_property IOSTANDARD LVCMOS33 [get_ports rst_btn]


set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAM_data_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports CAM_HSYNC_in]
set_property IOSTANDARD LVCMOS33 [get_ports CAM_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports CAM_pclk_in]
set_property IOSTANDARD LVCMOS33 [get_ports CAM_rstb]




set_property IOSTANDARD LVCMOS33 [get_ports CAM_stdby]
set_property IOSTANDARD LVCMOS33 [get_ports CAM_VSYNC_in]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_IF_pclk_out]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_IF_DE_out]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_dith]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_DRV_ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_IF_HSYNC_out]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_mode]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_IF_pdata_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_rstb]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_shlr]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_updn]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_IF_VSYNC_out]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_A_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PMOD_B_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports Touch_Intr]
set_property PULLDOWN true [get_ports Touch_Intr]
set_property IOSTANDARD LVCMOS33 [get_ports Touch_rstb]
set_property IOSTANDARD LVCMOS33 [get_ports Touch_I2C_scl]
set_property IOSTANDARD LVCMOS33 [get_ports Touch_I2C_sda]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_W_LED_ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_W_LED_en]



set_property PACKAGE_PIN R18 [get_ports rst_btn]


set_property PACKAGE_PIN P21 [get_ports {CAM_data_in[0]}]
set_property PACKAGE_PIN P20 [get_ports {CAM_data_in[1]}]
set_property PACKAGE_PIN L17 [get_ports {CAM_data_in[2]}]
set_property PACKAGE_PIN J22 [get_ports {CAM_data_in[3]}]
set_property PACKAGE_PIN J21 [get_ports {CAM_data_in[4]}]
set_property PACKAGE_PIN M17 [get_ports {CAM_data_in[5]}]
set_property PACKAGE_PIN R20 [get_ports {CAM_data_in[6]}]
set_property PACKAGE_PIN R21 [get_ports {CAM_data_in[7]}]
set_property PACKAGE_PIN J18 [get_ports {CAM_data_in[8]}]
set_property PACKAGE_PIN K18 [get_ports {CAM_data_in[9]}]
set_property PACKAGE_PIN B19 [get_ports CAM_HSYNC_in]
set_property PACKAGE_PIN B20 [get_ports CAM_VSYNC_in]

# set_property PACKAGE_PIN R21 [get_ports {CAM_data_in[0]}]
# set_property PACKAGE_PIN R20 [get_ports {CAM_data_in[1]}]
# set_property PACKAGE_PIN J21 [get_ports {CAM_data_in[2]}]
# set_property PACKAGE_PIN J22 [get_ports {CAM_data_in[3]}]
# set_property PACKAGE_PIN L17 [get_ports {CAM_data_in[4]}]
# set_property PACKAGE_PIN M17 [get_ports {CAM_data_in[5]}]
# set_property PACKAGE_PIN P20 [get_ports {CAM_data_in[6]}]
# set_property PACKAGE_PIN P21 [get_ports {CAM_data_in[7]}]
# set_property PACKAGE_PIN B20 [get_ports {CAM_data_in[8]}]
# set_property PACKAGE_PIN B19 [get_ports {CAM_data_in[9]}]
# set_property PACKAGE_PIN K18 [get_ports CAM_HSYNC_in]
# set_property PACKAGE_PIN J18 [get_ports CAM_VSYNC_in]

set_property PACKAGE_PIN N19 [get_ports CAM_mclk]
set_property PACKAGE_PIN D18 [get_ports CAM_pclk_in]
set_property PACKAGE_PIN L22 [get_ports CAM_rstb]
set_property PACKAGE_PIN L21 [get_ports CAM_stdby]

set_property PACKAGE_PIN F18 [get_ports {LCD_IF_pdata_out[0]}]
set_property PACKAGE_PIN G19 [get_ports {LCD_IF_pdata_out[1]}]
set_property PACKAGE_PIN G16 [get_ports {LCD_IF_pdata_out[2]}]
set_property PACKAGE_PIN D21 [get_ports {LCD_IF_pdata_out[3]}]
set_property PACKAGE_PIN G15 [get_ports {LCD_IF_pdata_out[4]}]
set_property PACKAGE_PIN G21 [get_ports {LCD_IF_pdata_out[5]}]
set_property PACKAGE_PIN G20 [get_ports {LCD_IF_pdata_out[6]}]
set_property PACKAGE_PIN E21 [get_ports {LCD_IF_pdata_out[7]}]
set_property PACKAGE_PIN L18 [get_ports LCD_IF_pclk_out]
set_property PACKAGE_PIN D15 [get_ports LCD_IF_DE_out]
set_property PACKAGE_PIN A21 [get_ports LCD_dith]
set_property PACKAGE_PIN K20 [get_ports LCD_DRV_ctrl]
set_property PACKAGE_PIN A19 [get_ports {LCD_IF_pdata_out[8]}]
set_property PACKAGE_PIN C22 [get_ports {LCD_IF_pdata_out[9]}]
set_property PACKAGE_PIN A18 [get_ports {LCD_IF_pdata_out[10]}]
set_property PACKAGE_PIN D22 [get_ports {LCD_IF_pdata_out[11]}]
set_property PACKAGE_PIN E18 [get_ports {LCD_IF_pdata_out[12]}]
set_property PACKAGE_PIN E20 [get_ports {LCD_IF_pdata_out[13]}]
set_property PACKAGE_PIN F19 [get_ports {LCD_IF_pdata_out[14]}]
set_property PACKAGE_PIN E19 [get_ports {LCD_IF_pdata_out[15]}]
set_property PACKAGE_PIN J16 [get_ports LCD_IF_HSYNC_out]
set_property PACKAGE_PIN E15 [get_ports LCD_mode]
set_property PACKAGE_PIN B17 [get_ports {LCD_IF_pdata_out[16]}]
set_property PACKAGE_PIN B16 [get_ports {LCD_IF_pdata_out[17]}]
set_property PACKAGE_PIN A17 [get_ports {LCD_IF_pdata_out[18]}]
set_property PACKAGE_PIN A16 [get_ports {LCD_IF_pdata_out[20]}]
set_property PACKAGE_PIN C18 [get_ports {LCD_IF_pdata_out[21]}]
set_property PACKAGE_PIN C17 [get_ports {LCD_IF_pdata_out[22]}]




set_property PACKAGE_PIN C19 [get_ports LCD_rstb]
set_property PACKAGE_PIN B15 [get_ports LCD_shlr]
set_property PACKAGE_PIN B21 [get_ports LCD_updn]
set_property PACKAGE_PIN J17 [get_ports LCD_IF_VSYNC_out]
set_property PACKAGE_PIN M21 [get_ports {PMOD_A_tri_io[0]}]
set_property PACKAGE_PIN N22 [get_ports {PMOD_A_tri_io[1]}]
set_property PACKAGE_PIN M20 [get_ports {PMOD_A_tri_io[2]}]
set_property PACKAGE_PIN M19 [get_ports {PMOD_A_tri_io[3]}]
set_property PACKAGE_PIN P22 [get_ports {PMOD_A_tri_io[4]}]
set_property PACKAGE_PIN P18 [get_ports {PMOD_A_tri_io[5]}]
set_property PACKAGE_PIN P17 [get_ports {PMOD_A_tri_io[6]}]
set_property PACKAGE_PIN L19 [get_ports {PMOD_A_tri_io[7]}]
set_property PACKAGE_PIN C15 [get_ports {PMOD_B_tri_io[0]}]
set_property PACKAGE_PIN J20 [get_ports {PMOD_B_tri_io[1]}]
set_property PACKAGE_PIN N17 [get_ports {PMOD_B_tri_io[2]}]
set_property PACKAGE_PIN T16 [get_ports {PMOD_B_tri_io[3]}]
set_property PACKAGE_PIN K21 [get_ports {PMOD_B_tri_io[4]}]
set_property PACKAGE_PIN N18 [get_ports {PMOD_B_tri_io[5]}]
set_property PACKAGE_PIN T17 [get_ports {PMOD_B_tri_io[6]}]
set_property PACKAGE_PIN M22 [get_ports {PMOD_B_tri_io[7]}]
set_property PACKAGE_PIN T19 [get_ports Touch_Intr]
set_property PACKAGE_PIN R19 [get_ports Touch_rstb]
set_property PACKAGE_PIN A22 [get_ports Touch_I2C_scl]
set_property PACKAGE_PIN B22 [get_ports Touch_I2C_sda]
set_property PACKAGE_PIN K19 [get_ports LCD_W_LED_ctrl]
set_property PACKAGE_PIN N20 [get_ports LCD_W_LED_en]




# user define end



set_property DRIVE 16 [get_ports CAM_I2C_scl]
set_property DRIVE 16 [get_ports CAM_I2C_sda]
set_property SLEW FAST [get_ports CAM_I2C_scl]
set_property SLEW FAST [get_ports CAM_I2C_sda]

create_clock -period 6.734 -name cam_pclk -waveform {0.000 3.367} [get_ports CAM_pclk_in]
set_input_delay -clock [get_clocks *pclk*] -add_delay 6.734 [get_ports {{CAM_data_in[0]} {CAM_data_in[1]} {CAM_data_in[2]} {CAM_data_in[3]} {CAM_data_in[4]} {CAM_data_in[5]} {CAM_data_in[6]} {CAM_data_in[7]} {CAM_data_in[8]} {CAM_data_in[9]} CAM_HSYNC_in CAM_VSYNC_in}]










set_property SLEW FAST [get_ports {LCD_IF_pdata_out[23]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[22]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[21]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[20]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[19]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[18]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[17]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[16]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[15]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[14]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[13]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[12]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[11]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[10]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[9]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[8]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[7]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[6]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[5]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[4]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[3]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[2]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[1]}]
set_property SLEW FAST [get_ports {LCD_IF_pdata_out[0]}]
set_property SLEW FAST [get_ports LCD_IF_pclk_out]
set_property SLEW FAST [get_ports CAM_mclk]
set_property SLEW FAST [get_ports LCD_IF_HSYNC_out]
set_property SLEW FAST [get_ports LCD_IF_VSYNC_out]
set_property SLEW FAST [get_ports LCD_IF_DE_out]
set_property DRIVE 8 [get_ports LCD_IF_pclk_out]
set_property DRIVE 8 [get_ports LCD_IF_DE_out]
set_property DRIVE 8 [get_ports LCD_IF_HSYNC_out]
set_property DRIVE 8 [get_ports LCD_IF_VSYNC_out]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[23]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[22]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[21]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[20]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[19]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[18]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[17]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[16]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[15]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[14]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[13]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[12]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[11]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[10]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[9]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[8]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[7]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[6]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[5]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[4]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[3]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[2]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[1]}]
set_property DRIVE 8 [get_ports {LCD_IF_pdata_out[0]}]